# Dockerfile_frontend
FROM node:20.11.1 as build
WORKDIR /app/frontend
COPY frontend .
RUN npm install
RUN npm run build

# nginx
FROM nginx:1.21
WORKDIR /usr/share/nginx/html
COPY --from=build /app/frontend/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
