
version: "3"

services:
  ngnix-react:
    image: egovernance-app:latest
    container_name: container-egovernance-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 5000:5000
    environment:
      - NODE_ENV=production

