version: '3'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  nginx:
    image: nginx:1.21
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - PORT=80
