# Dockerfile_backend
FROM python:3.12.2 as flask
WORKDIR /app/backend
COPY backend .

RUN pip install --upgrade pip && pip install gunicorn
RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["gunicorn", "run:app", "--bind", "0.0.0.0:5000"]

# Create a standalone Gunicorn image
FROM python:3.12.2 as gunicorn
COPY --from=flask /usr/local/bin/gunicorn /usr/local/bin/gunicorn
