version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000  # Adjust the backend URL as needed

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "5000:5000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "8080:80"  # Map port 8080 to avoid conflicts with frontend's port 80
    depends_on:
      - frontend
      - backend
