# Dockerfile_backend
FROM python:3.12.2 as flask
WORKDIR /app/backend
COPY backend .

RUN pip install --upgrade pip && pip install -r requirements.txt
RUN pip install gunicorn

EXPOSE 5000
CMD ["gunicorn", "run:app", "--bind", "0.0.0.0:5000"]
