# Dockerfile_frontend
FROM node:20.11.1 as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM nginx:1.21
WORKDIR /usr/share/nginx/html
COPY --from=build /app/build .

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
