# Use the official Python image as a base image
FROM python:3.12.2

# Set the working directory to /app/backend
WORKDIR /app/backend

# Copy the backend directory contents into the container at /app/backend
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt 

# Expose port 5000 for Flask app
EXPOSE 5000

# Define environment variable to run Flask app
ENV FLASK_APP=run.py

# Command to run the Flask application
CMD ["gunicorn", "run:app", "--bind", "0.0.0.0:5000"]
