# Dockerfile_backend
FROM python:3.12.2 as flask
WORKDIR /app/backend
COPY backend .

RUN pip install --upgrade pip && \
    pip install gunicorn && \
    pip install -r requirements.txt

EXPOSE 5000
CMD ["python", "application.py"]
